name: CI/CD Pipeline for Frontend and Backend

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      BACKEND_REPO_NAME: "doctor-office-backend"
      FRONTEND_REPO_NAME: "doctor-office-frontend"
      BACKEND_PATH: "./doctor-office-backend"
      FRONTEND_PATH: "./doctor-office-frontend"
      IMAGE_TAG: "latest"

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.24.0'  # default is latest stable
        id: install
  
      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      # Step 4: Verify ECR Registry Output
      - name: Debug ECR Registry
        run: echo "ECR Registry:${{ steps.login-ecr.outputs.registry }}"

      # Step 5: Build, Tag, and Push Backend Image
      - name: Build and Push Backend Docker image
        run: |
          docker build -t ${{ env.BACKEND_REPO_NAME }} ${{ env.BACKEND_PATH }}
          docker tag ${{ env.BACKEND_REPO_NAME }} ${{ steps.login-ecr.outputs.registry }}/${{ env.BACKEND_REPO_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.BACKEND_REPO_NAME }}:${{ env.IMAGE_TAG }}

      # Step 6: Build, Tag, and Push Frontend Image
      - name: Build and Push Frontend Docker image
        run: |
          docker build -t ${{ env.FRONTEND_REPO_NAME }} ${{ env.FRONTEND_PATH }}
          docker tag ${{ env.FRONTEND_REPO_NAME }} ${{ steps.login-ecr.outputs.registry }}/${{ env.FRONTEND_REPO_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.FRONTEND_REPO_NAME }}:${{ env.IMAGE_TAG }}

      # Step 7: Update kube config to connect to EKS
      - name: Update kube config
        run: aws eks update-kubeconfig --name group8
